# Project: testportaudio
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = portaudiotesttone.o
LINKOBJ  = portaudiotesttone.o
LIBS     = -L"D:/Programming/Dev-Cpp/MinGW32/lib" -L"D:/Programming/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc C:/MinGW/msys/1.0/local/lib/libportaudio.dll.a C:/MinGW/msys/1.0/local/lib/libportaudio.la C:/MinGW/msys/1.0/local/bin/libportaudio-2.dll ../../Programming/Dev-Cpp/MinGW32/lib/libwinmm.a -g3
INCS     = -I"D:/Programming/Dev-Cpp/MinGW32/include" -I"D:/Programming/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"D:/Programming/Dev-Cpp/MinGW32/include" -I"D:/Programming/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = testportaudio.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

portaudiotesttone.o: portaudiotesttone.c
	$(CC) -c portaudiotesttone.c -o portaudiotesttone.o $(CFLAGS)
