# Project: TestTone
# Makefile created by Dev-C++ 5.7.1

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/Programming/Dev-Cpp/MinGW32/lib" -L"D:/Programming/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc ../../Programming/Dev-Cpp/MinGW32/lib/NIDAQmx.lib -g3
INCS     = -I"D:/Programming/Dev-Cpp/MinGW32/include" -I"D:/Programming/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"D:/Programming/Dev-Cpp/MinGW32/include" -I"D:/Programming/Dev-Cpp/MinGW32/mingw32/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"D:/Programming/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = TestTone.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
